name: Deploy Inference (GPU L4)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-gpu:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Set gcloud project
        run: gcloud config set project "${{ vars.GCP_PROJECT_ID }}"

      - name: Configure Artifact Registry Docker auth
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (AMD64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/dockerfiles/Dockerfile.gpu
          push: true
          platforms: linux/amd64
          tags: ${{ vars.AR_REPO }}/infer-gpu:${{ github.sha }}

      - name: Deploy Cloud Run (GPU L4)
        run: |
          gcloud run deploy infer-gpu \
            --image "${{ vars.AR_REPO }}/infer-gpu:${{ github.sha }}" \
            --region "${{ vars.GCP_REGION }}" \
            --platform managed \
            --allow-unauthenticated \
            --gpu 1 --gpu-type nvidia-l4 --no-gpu-zonal-redundancy \
            --cpu 4 --memory 16Gi --no-cpu-throttling \
            --concurrency 1 \
            --service-account "run-infer@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com" \
            --min-instances 0 --max-instances 1
