name: Train Detector (Cloud Batch GPU)

on:
  workflow_dispatch:
    inputs:
      dataset_gcs_uri:
        description: "gs://.../datasets/<name> (must contain data.yaml)"
        required: true
      out_gcs_uri:
        description: "gs://.../models/<run_name>"
        required: true
      epochs:
        description: "Epochs"
        default: "100"
      imgsz:
        description: "Image size"
        default: "1024"
      base_model:
        description: "Ultralytics base (e.g., yolov8m.pt)"
        default: "yolov8m.pt"
      gpu_type:
        description: "GPU type: nvidia-l4 or nvidia-tesla-t4"
        default: "nvidia-l4"
      machine_type:
        description: "Machine type (g2-standard-4 for L4, n1-standard-8 for T4)"
        default: "g2-standard-4"
      provisioning_model:
        description: "STANDARD or SPOT"
        default: "STANDARD"
      allowed_zones_csv:
        description: "Comma-separated zones (e.g., us-central1-a,us-central1-b,us-central1-c,us-central1-f)"
        default: "us-central1-a,us-central1-b,us-central1-c,us-central1-f"

jobs:
  train:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.GCP_WIF_PROVIDER }}
          service_account: ${{ vars.GCP_SERVICE_ACCOUNT_EMAIL }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project "${{ vars.GCP_PROJECT_ID }}"

      - name: Build & Push training image
        run: |
          IMAGE="${{ vars.AR_REPO }}/train:${{ github.sha }}"
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev --quiet
          docker build -t "$IMAGE" -f deploy/dockerfiles/Dockerfile.train .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Submit Cloud Batch job (GPU)
        run: |
          JOB="train-detector-${{ github.run_id }}"
          DATASET="${{ github.event.inputs.dataset_gcs_uri }}"
          OUT="${{ github.event.inputs.out_gcs_uri }}"
          EPOCHS="${{ github.event.inputs.epochs }}"
          IMGSZ="${{ github.event.inputs.imgsz }}"
          BASE="${{ github.event.inputs.base_model }}"
          GPU_TYPE="${{ github.event.inputs.gpu_type }}"
          MACHINE_TYPE="${{ github.event.inputs.machine_type }}"
          PROV="${{ github.event.inputs.provisioning_model }}"
          ZCSV="${{ github.event.inputs.allowed_zones_csv }}"
          SA_EMAIL="batch-runner@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

          # Build allowedLocations JSON from CSV (["zones/us-central1-a", ...])
          ALLOWED_JSON=$(jq -cn --arg csv "$ZCSV" '$csv|split(",")|map(gsub("^\\s+|\\s+$";"")|select(length>0)|"zones/\(.)")')

          cat > job.json <<EOF
          {
            "taskGroups": [{
              "taskCount": 1,
              "taskSpec": {
                "computeResource": { "cpuMilli": 8000, "memoryMib": 16384 },
                "maxRunDuration": "3600s",
                "maxRetryCount": 2,
                "runnables": [{
                  "container": {
                    "imageUri": "${IMAGE}",
                    "commands": [
                      "python","pipeline/train_detector.py",
                      "--data_uri","${DATASET}",
                      "--out_uri","${OUT}",
                      "--epochs","${EPOCHS}",
                      "--imgsz","${IMGSZ}",
                      "--base","${BASE}"
                    ]
                  }
                }]
              }
            }],
            "allocationPolicy": {
              "serviceAccount": { "email": "${SA_EMAIL}" },
              "location": { "allowedLocations": ${ALLOWED_JSON} },
              "instances": [{
                "installGpuDrivers": true,
                "policy": {
                  "machineType": "${MACHINE_TYPE}",
                  "provisioningModel": "${PROV}",
                  "accelerators": [{ "type": "${GPU_TYPE}", "count": 1 }]
                }
              }]
            },
            "logsPolicy": { "destination": "CLOUD_LOGGING" }
          }
          EOF

          gcloud batch jobs submit "$JOB" \
            --location "${{ vars.GCP_REGION }}" \
            --config job.json

          echo "JOB=$JOB" >> $GITHUB_ENV

      - name: Show job link
        run: |
          echo "Job: $JOB"
          echo "Console: https://console.cloud.google.com/batch/jobs/$JOB/details?project=${{ vars.GCP_PROJECT_ID }}&location=${{ vars.GCP_REGION }}"
