      - name: Submit Cloud Batch job (Spot L4, 60m cap)
        run: |
          JOB="train-detector-${{ github.run_id }}"
          DATASET="${{ github.event.inputs.dataset_gcs_uri }}"
          OUT="${{ github.event.inputs.out_gcs_uri }}"
          EPOCHS="${{ github.event.inputs.epochs }}"
          IMGSZ="${{ github.event.inputs.imgsz }}"
          BASE="${{ github.event.inputs.base_model }}"
          SA_EMAIL="batch-runner@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

          cat > job.json <<EOF
          {
            "taskGroups": [{
              "taskCount": 1,
              "taskSpec": {
                "serviceAccount": { "email": "${SA_EMAIL}" },
                "computeResource": { "cpuMilli": 8000, "memoryMib": 16384 },
                "maxRunDuration": "3600s",
                "runnables": [{
                  "container": {
                    "imageUri": "${IMAGE}",
                    "commands": [
                      "python","pipeline/train_detector.py",
                      "--data_uri","${DATASET}",
                      "--out_uri","${OUT}",
                      "--epochs","${EPOCHS}",
                      "--imgsz","${IMGSZ}",
                      "--base","${BASE}"
                    ]
                  }
                }]
              }
            }],
            "allocationPolicy": {
              "instances": [{
                "policy": {
                  "machineType": "g2-standard-4",
                  "provisioningModel": "SPOT",
                  "accelerators": [{ "type": "nvidia-l4", "count": 1 }]
                },
                "installGpuDrivers": true
              }]
            },
            "logsPolicy": { "destination": "CLOUD_LOGGING" }
          }
          EOF

          gcloud batch jobs submit "$JOB" \
            --location "${{ vars.GCP_REGION }}" \
            --config job.json

          echo "JOB=$JOB" >> $GITHUB_ENV

